### ISSUE TITLE
not working after 1epoch

### ISSUE THREAD

**Issue by nadongjin** [leondgarse/Keras_insightface#68]
It worked well in the old github code.
However, in the current github code, the following error occurs after 1epoch as follows.
[TypeError: unsupported operand type(s) for +: 'PerReplica' and 'PerReplica']
thanks...
#===================================================================================
Evaluating lfw:   0%|          | 0/63 [00:00<?, ?it/s]WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.
Evaluating lfw:   0%|          | 0/63 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:/Users/facetag/Face_project/my_insight2/real_train.py", line 44, in <module>
    tt.train(sch, 0)
  File "C:\Users\facetag\Face_project\my_insight2\train.py", line 460, in train
    self.train_single_scheduler(**sch, initial_epoch=initial_epoch)
  File "C:\Users\facetag\Face_project\my_insight2\train.py", line 443, in train_single_scheduler
    self.__basic_train__(initial_epoch + epoch, initial_epoch=initial_epoch)
  File "C:\Users\facetag\Face_project\my_insight2\train.py", line 349, in __basic_train__
    workers=4,
  File "C:\Users\facetag\Face_project\venv\lib\site-packages\keras\engine\training.py", line 1230, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\facetag\Face_project\venv\lib\site-packages\keras\callbacks.py", line 413, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\facetag\Face_project\my_insight2\evals.py", line 37, in <lambda>
    self.on_epoch_end = lambda epoch=0, logs=None: self.__eval_func__(epoch, logs, eval_freq=1)
  File "C:\Users\facetag\Face_project\my_insight2\evals.py", line 87, in __eval_func__
    embs = self.__do_predict_distribute__()
  File "C:\Users\facetag\Face_project\my_insight2\evals.py", line 68, in __do_predict_distribute__
    emb = emb + emb_f
TypeError: unsupported operand type(s) for +: 'PerReplica' and 'PerReplica'

**Comment by leondgarse** [comment]
Uh, It's caused by a change in `evals.py`, that my trying to fit `TF 2.8.0`, reversed. Currently will not work for `TF 2.8.0-rc0`. I may take more tests, and change that part again.

**Comment by leondgarse** [comment]
It should work for both `TF 2.8.0` and earlier version now.

**Comment by leondgarse** [comment]
Fix again... Seems I need more tests on this...
